/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* ───── Semantic (theme-aware) tokens ───── */
        canvas: 'rgb(var(--canvas) / <alpha-value>)',
        surface: {
          DEFAULT: 'rgb(var(--surface) / <alpha-value>)',
          elevated: 'rgb(var(--surface-elevated) / <alpha-value>)',
          higher: 'rgb(var(--surface-higher) / <alpha-value>)',
        },
        line: {
          DEFAULT: 'rgb(var(--line) / <alpha-value>)',
          strong: 'rgb(var(--line-strong) / <alpha-value>)',
        },
        ink: {
          DEFAULT: 'rgb(var(--ink) / <alpha-value>)',
          muted: 'rgb(var(--ink-muted) / <alpha-value>)',
          dim: 'rgb(var(--ink-dim) / <alpha-value>)',
        },
        active: 'rgb(var(--active-bg) / <alpha-value>)',
        brand: {
          DEFAULT: 'rgb(var(--brand) / <alpha-value>)',
          violet: 'rgb(var(--brand-2) / <alpha-value>)',
          glow: 'rgb(var(--brand) / <alpha-value>)',
          soft: 'rgb(var(--brand-soft) / <alpha-value>)',
        },
        accent: {
          warm: 'rgb(var(--accent-warm) / <alpha-value>)',
        },

        /* ───── Raw design tokens — base palette ───── */
        sand: {
          0:  'var(--color-base-sand-0)',
          10: 'var(--color-base-sand-10)',
          20: 'var(--color-base-sand-20)',
          30: 'var(--color-base-sand-30)',
          40: 'var(--color-base-sand-40)',
          50: 'var(--color-base-sand-50)',
          60: 'var(--color-base-sand-60)',
          70: 'var(--color-base-sand-70)',
          80: 'var(--color-base-sand-80)',
          90: 'var(--color-base-sand-90)',
        },
        ocean: {
          10: 'var(--color-base-ocean-10)', 20: 'var(--color-base-ocean-20)',
          30: 'var(--color-base-ocean-30)', 40: 'var(--color-base-ocean-40)',
          50: 'var(--color-base-ocean-50)', 60: 'var(--color-base-ocean-60)',
          70: 'var(--color-base-ocean-70)', 80: 'var(--color-base-ocean-80)',
        },
        rust: {
          10: 'var(--color-base-rust-10)', 20: 'var(--color-base-rust-20)',
          30: 'var(--color-base-rust-30)', 40: 'var(--color-base-rust-40)',
          50: 'var(--color-base-rust-50)', 60: 'var(--color-base-rust-60)',
          70: 'var(--color-base-rust-70)', 80: 'var(--color-base-rust-80)',
        },
        pebble: {
          10: 'var(--color-base-pebble-10)', 20: 'var(--color-base-pebble-20)',
          30: 'var(--color-base-pebble-30)', 40: 'var(--color-base-pebble-40)',
          50: 'var(--color-base-pebble-50)', 60: 'var(--color-base-pebble-60)',
          70: 'var(--color-base-pebble-70)', 80: 'var(--color-base-pebble-80)',
        },
        sakura: {
          10: 'var(--color-base-sakura-10)', 20: 'var(--color-base-sakura-20)',
          30: 'var(--color-base-sakura-30)', 40: 'var(--color-base-sakura-40)',
          50: 'var(--color-base-sakura-50)', 60: 'var(--color-base-sakura-60)',
          70: 'var(--color-base-sakura-70)', 80: 'var(--color-base-sakura-80)',
        },
        iris: {
          10: 'var(--color-base-iris-10)', 20: 'var(--color-base-iris-20)',
          30: 'var(--color-base-iris-30)', 40: 'var(--color-base-iris-40)',
          50: 'var(--color-base-iris-50)', 60: 'var(--color-base-iris-60)',
          70: 'var(--color-base-iris-70)', 80: 'var(--color-base-iris-80)',
        },
        moss: {
          10: 'var(--color-base-moss-10)', 20: 'var(--color-base-moss-20)',
          30: 'var(--color-base-moss-30)', 40: 'var(--color-base-moss-40)',
          50: 'var(--color-base-moss-50)', 60: 'var(--color-base-moss-60)',
          70: 'var(--color-base-moss-70)', 80: 'var(--color-base-moss-80)',
        },
        tropic: {
          10: 'var(--color-base-tropic-10)', 20: 'var(--color-base-tropic-20)',
          30: 'var(--color-base-tropic-30)', 40: 'var(--color-base-tropic-40)',
          50: 'var(--color-base-tropic-50)', 60: 'var(--color-base-tropic-60)',
          70: 'var(--color-base-tropic-70)', 80: 'var(--color-base-tropic-80)',
        },
        evergreen: {
          10: 'var(--color-base-evergreen-10)', 20: 'var(--color-base-evergreen-20)',
          30: 'var(--color-base-evergreen-30)', 40: 'var(--color-base-evergreen-40)',
          50: 'var(--color-base-evergreen-50)', 60: 'var(--color-base-evergreen-60)',
          70: 'var(--color-base-evergreen-70)', 80: 'var(--color-base-evergreen-80)',
        },
        ember: {
          10: 'var(--color-base-ember-10)', 20: 'var(--color-base-ember-20)',
          30: 'var(--color-base-ember-30)', 40: 'var(--color-base-ember-40)',
          50: 'var(--color-base-ember-50)', 60: 'var(--color-base-ember-60)',
          70: 'var(--color-base-ember-70)', 80: 'var(--color-base-ember-80)',
        },
        sunbeam: {
          10: 'var(--color-base-sunbeam-10)',
          30: 'var(--color-base-sunbeam-30)',
          50: 'var(--color-base-sunbeam-50)',
          70: 'var(--color-base-sunbeam-70)',
        },

        /* Alpha tokens — translucent overlays / tints */
        alpha: {
          'highlight-0': 'var(--color-base-alpha-highlight-0)',
          'highlight-1': 'var(--color-base-alpha-highlight-1)',
          'highlight-2': 'var(--color-base-alpha-highlight-2)',
          'shadow-0': 'var(--color-base-alpha-shadow-0)',
          'shadow-1': 'var(--color-base-alpha-shadow-1)',
          'shadow-2': 'var(--color-base-alpha-shadow-2)',
          'shadow-3': 'var(--color-base-alpha-shadow-3)',
          'shadow-4': 'var(--color-base-alpha-shadow-4)',
          'shadow-5': 'var(--color-base-alpha-shadow-5)',
          'shadow-6': 'var(--color-base-alpha-shadow-6)',
          'shadow-7': 'var(--color-base-alpha-shadow-7)',
          border: 'var(--color-base-alpha-border)',
          overlay: 'var(--color-base-alpha-overlay)',
          'overlay-inverse': 'var(--color-base-alpha-overlay-inverse)',
          'moss-10': 'var(--color-base-alpha-moss-10)',
          'moss-20': 'var(--color-base-alpha-moss-20)',
          'iris-10': 'var(--color-base-alpha-iris-10)',
          'iris-20': 'var(--color-base-alpha-iris-20)',
          'sakura-10': 'var(--color-base-alpha-sakura-10)',
          'sakura-20': 'var(--color-base-alpha-sakura-20)',
          'pebble-10': 'var(--color-base-alpha-pebble-10)',
          'pebble-20': 'var(--color-base-alpha-pebble-20)',
          'tropic-10': 'var(--color-base-alpha-tropic-10)',
          'tropic-20': 'var(--color-base-alpha-tropic-20)',
          'rust-10': 'var(--color-base-alpha-rust-10)',
          'rust-20': 'var(--color-base-alpha-rust-20)',
          'ember-10': 'var(--color-base-alpha-ember-10)',
          'ember-20': 'var(--color-base-alpha-ember-20)',
          'evergreen-10': 'var(--color-base-alpha-evergreen-10)',
          'evergreen-20': 'var(--color-base-alpha-evergreen-20)',
          'ocean-10': 'var(--color-base-alpha-ocean-10)',
          'ocean-20': 'var(--color-base-alpha-ocean-20)',
          'sunbeam-10': 'var(--color-base-alpha-sunbeam-10)',
          'sunbeam-20': 'var(--color-base-alpha-sunbeam-20)',
        },

        /* Elevation surfaces — paper-white in light, tinted in dark */
        elevation: {
          1: 'var(--color-base-elevation-elevation-1)',
          2: 'var(--color-base-elevation-elevation-2)',
          3: 'var(--color-base-elevation-elevation-3)',
          4: 'var(--color-base-elevation-elevation-4)',
          5: 'var(--color-base-elevation-elevation-5)',
        },

        /* Brand integrations */
        hubspot: {
          10: 'var(--color-brand-hubspot-10)',
          50: 'var(--color-brand-hubspot-50)',
        },
        linkedin: {
          10: 'var(--color-brand-linkedin-10)',
          50: 'var(--color-brand-linkedin-50)',
        },

        constants: {
          dark: 'var(--color-constants-dark)',
          light: 'var(--color-constants-light)',
        },

        /* Data visualization palette */
        data: {
          'yellow-10': 'var(--color-data-yellow-10)', 'yellow-20': 'var(--color-data-yellow-20)',
          'yellow-30': 'var(--color-data-yellow-30)', 'yellow-40': 'var(--color-data-yellow-40)',
          'yellow-50': 'var(--color-data-yellow-50)', 'yellow-60': 'var(--color-data-yellow-60)',
          'yellow-70': 'var(--color-data-yellow-70)', 'yellow-80': 'var(--color-data-yellow-80)',
          'olive-10': 'var(--color-data-olive-10)', 'olive-20': 'var(--color-data-olive-20)',
          'olive-30': 'var(--color-data-olive-30)', 'olive-40': 'var(--color-data-olive-40)',
          'olive-50': 'var(--color-data-olive-50)', 'olive-60': 'var(--color-data-olive-60)',
          'olive-70': 'var(--color-data-olive-70)', 'olive-80': 'var(--color-data-olive-80)',
          'green-10': 'var(--color-data-green-10)', 'green-20': 'var(--color-data-green-20)',
          'green-30': 'var(--color-data-green-30)', 'green-40': 'var(--color-data-green-40)',
          'green-50': 'var(--color-data-green-50)', 'green-60': 'var(--color-data-green-60)',
          'green-70': 'var(--color-data-green-70)', 'green-80': 'var(--color-data-green-80)',
          'turquoise-10': 'var(--color-data-turquoise-10)', 'turquoise-20': 'var(--color-data-turquoise-20)',
          'turquoise-30': 'var(--color-data-turquoise-30)', 'turquoise-40': 'var(--color-data-turquoise-40)',
          'turquoise-50': 'var(--color-data-turquoise-50)', 'turquoise-60': 'var(--color-data-turquoise-60)',
          'turquoise-70': 'var(--color-data-turquoise-70)', 'turquoise-80': 'var(--color-data-turquoise-80)',
          'blue-10': 'var(--color-data-blue-10)', 'blue-20': 'var(--color-data-blue-20)',
          'blue-30': 'var(--color-data-blue-30)', 'blue-40': 'var(--color-data-blue-40)',
          'blue-50': 'var(--color-data-blue-50)', 'blue-60': 'var(--color-data-blue-60)',
          'blue-70': 'var(--color-data-blue-70)', 'blue-80': 'var(--color-data-blue-80)',
          'violet-10': 'var(--color-data-violet-10)', 'violet-20': 'var(--color-data-violet-20)',
          'violet-30': 'var(--color-data-violet-30)', 'violet-40': 'var(--color-data-violet-40)',
          'violet-50': 'var(--color-data-violet-50)', 'violet-60': 'var(--color-data-violet-60)',
          'violet-70': 'var(--color-data-violet-70)', 'violet-80': 'var(--color-data-violet-80)',
          'purple-10': 'var(--color-data-purple-10)', 'purple-20': 'var(--color-data-purple-20)',
          'purple-30': 'var(--color-data-purple-30)', 'purple-40': 'var(--color-data-purple-40)',
          'purple-50': 'var(--color-data-purple-50)', 'purple-60': 'var(--color-data-purple-60)',
          'purple-70': 'var(--color-data-purple-70)', 'purple-80': 'var(--color-data-purple-80)',
          'pink-10': 'var(--color-data-pink-10)', 'pink-20': 'var(--color-data-pink-20)',
          'pink-30': 'var(--color-data-pink-30)', 'pink-40': 'var(--color-data-pink-40)',
          'pink-50': 'var(--color-data-pink-50)', 'pink-60': 'var(--color-data-pink-60)',
          'pink-70': 'var(--color-data-pink-70)', 'pink-80': 'var(--color-data-pink-80)',
          'red-10': 'var(--color-data-red-10)', 'red-20': 'var(--color-data-red-20)',
          'red-30': 'var(--color-data-red-30)', 'red-40': 'var(--color-data-red-40)',
          'red-50': 'var(--color-data-red-50)', 'red-60': 'var(--color-data-red-60)',
          'red-70': 'var(--color-data-red-70)', 'red-80': 'var(--color-data-red-80)',
          'orange-10': 'var(--color-data-orange-10)', 'orange-20': 'var(--color-data-orange-20)',
          'orange-30': 'var(--color-data-orange-30)', 'orange-40': 'var(--color-data-orange-40)',
          'orange-50': 'var(--color-data-orange-50)', 'orange-60': 'var(--color-data-orange-60)',
          'orange-70': 'var(--color-data-orange-70)', 'orange-80': 'var(--color-data-orange-80)',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['"Fraunces"', '"Iowan Old Style"', 'Georgia', 'serif'],
        display: ['"Fraunces"', '"Iowan Old Style"', 'Georgia', 'serif'],
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, rgb(var(--brand)) 0%, rgb(var(--brand-2)) 100%)',
        'card-gradient': 'linear-gradient(180deg, rgb(var(--brand) / 0.06) 0%, rgb(var(--brand) / 0) 100%)',
        'glow-radial': 'radial-gradient(60% 50% at 50% 0%, rgb(var(--brand) / 0.10) 0%, rgb(var(--brand) / 0) 100%)',
      },
      boxShadow: {
        'soft': '0 1px 0 rgb(var(--line) / 0.6), 0 12px 32px -16px rgba(0,0,0,0.55)',
        'card': '0 1px 0 rgb(var(--line) / 0.6)',
      },
      animation: {
        'fade-in':       'fadeIn 260ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up':      'slideUp 340ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in':      'slideIn 320ms cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in':      'scaleIn 220ms cubic-bezier(0.16, 1, 0.3, 1)',
        'pop-in':        'popIn 280ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'flow-right':    'flowRight 2.4s ease-in-out infinite',
        'flow-left':     'flowLeft 2.4s ease-in-out infinite 1.2s',
        'soft-pulse':    'softPulse 2.6s ease-in-out infinite',
        'spin-slow':     'spin 12s linear infinite',
        'spin-rev':      'spin 8s linear infinite reverse',
        'progress-fill': 'progressFill 1800ms cubic-bezier(0.45, 0, 0.15, 1) forwards',
        'float-a':       'floatA 3.6s ease-in-out infinite',
        'float-b':       'floatB 4.2s ease-in-out infinite 0.6s',
        'float-c':       'floatC 4.8s ease-in-out infinite 1.2s',
      },
      keyframes: {
        fadeIn: {
          '0%':   { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%':   { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%':   { opacity: '0', transform: 'translateX(24px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%':   { opacity: '0', transform: 'scale(0.94)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        popIn: {
          '0%':   { opacity: '0', transform: 'scale(0.92)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        flowRight: {
          '0%':   { transform: 'translateX(-46px) scale(0.6)', opacity: '0' },
          '15%':  { transform: 'translateX(-30px) scale(1)',   opacity: '1' },
          '85%':  { transform: 'translateX(30px) scale(1)',    opacity: '1' },
          '100%': { transform: 'translateX(46px) scale(0.6)',  opacity: '0' },
        },
        flowLeft: {
          '0%':   { transform: 'translateX(46px) scale(0.6)',  opacity: '0' },
          '15%':  { transform: 'translateX(30px) scale(1)',    opacity: '1' },
          '85%':  { transform: 'translateX(-30px) scale(1)',   opacity: '1' },
          '100%': { transform: 'translateX(-46px) scale(0.6)', opacity: '0' },
        },
        softPulse: {
          '0%, 100%': { transform: 'scale(1)',    opacity: '0.65' },
          '50%':      { transform: 'scale(1.18)', opacity: '0.35' },
        },
        progressFill: {
          '0%':   { transform: 'scaleX(0)' },
          '100%': { transform: 'scaleX(1)' },
        },
        floatA: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)',     opacity: '0.4' },
          '50%':      { transform: 'translate(8px, -10px) scale(1.3)', opacity: '1' },
        },
        floatB: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)',      opacity: '0.5' },
          '50%':      { transform: 'translate(-6px, -8px) scale(1.4)', opacity: '1' },
        },
        floatC: {
          '0%, 100%': { transform: 'translate(0, 0) scale(0.9)',    opacity: '0.3' },
          '50%':      { transform: 'translate(5px, 6px) scale(1.2)',  opacity: '0.9' },
        },
      },
    },
  },
  plugins: [],
}
